Adds a setting for default lane size
open-rmf/rmf_site pull request #135
Opened 2023-05-26 08:45 UTC by arjo129

This PR adds a setting for default lane size. It can be found by going to `Edit -> Preferences...`. We need to find a way to persist this. Note this setting does not change per-lane widths as those should be handled differently.

2023-06-06 07:25 UTC, luca-della-vedova requested changes
A good start on the feature, not sure whether it's ok for the long term but probed a bit around the implementation and found a few issues that should be addressed if we want to get this in.

It seems that when the default lane width is set and a new lane is created a fair bit of glitches appear, as in the video below:


Specifically the beginning and end of each lane go back to the original width. Measurements are also scaled

2023-06-06 07:25 UTC, luca-della-vedova commented on rmf_site_editor/src/widgets/preferences.rs
> +                        .clamp_range(0.0..=10000.0);
`0.0` is a bit of a risky lower bound that would make it completely invisible, I'd suggest making it something that is not completely invisible but still covers the lowest common case (maybe 0.1 m?)

2023-06-07 00:31 UTC, arjo129 commented
Will fix these however in another conversation with @mxgrey he mentioned the following crate: https://github.com/ForesightMiningSoftwareCorporation/bevy_polyline

This removes the need for this feature. Will probably use this instead.

2023-07-18 05:54 UTC, arjo129 commented
Closing in favor of #152

2023-07-18 05:54 UTC, closed without merging